import type { DataConnection, SchemaTable } from "./types";

export const demoConnection: DataConnection = {
  id: "warehouse-demo",
  name: "Northstar revenue warehouse",
  kind: "postgresql",
  host: "analytics.northstar.internal",
  status: "connected",
  latencyMs: 84,
  lastIntrospectedAt: "2026-09-17T09:30:00.000Z",
  tables: 6,
};

const measure = (
  sampleValues: string[],
  cardinality: number,
  min: number | null = null,
  max: number | null = null,
) => ({
  nullRate: 0,
  cardinality,
  min,
  max,
  sampleValues,
});

export const schemaCatalog: SchemaTable[] = [
  {
    name: "orders",
    rowCount: 184203,
    relevance: 0.99,
    columns: [
      {
        name: "order_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Unique order identifier.",
        metrics: measure(["100492", "100493", "100494"], 184203, 100001, 284203),
      },
      {
        name: "customer_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Customer who placed the order.",
        metrics: measure(["c_1042", "c_1177", "c_2088"], 16408),
      },
      {
        name: "ordered_at",
        dataType: "timestamp",
        nullable: false,
        semanticType: "time",
        description: "UTC timestamp when the order was placed.",
        metrics: measure(["2026-01-08", "2026-02-14", "2026-03-02"], 548, null, null),
      },
      {
        name: "net_revenue",
        dataType: "numeric(12,2)",
        nullable: false,
        semanticType: "measure",
        description: "Revenue after discounts and before tax.",
        metrics: measure(["124.00", "580.50", "1840.00"], 87320, 4.5, 24890),
      },
      {
        name: "status",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Order lifecycle status.",
        metrics: measure(["paid", "fulfilled", "refunded"], 5),
      },
    ],
    foreignKeys: [{ fromColumn: "customer_id", toTable: "customers", toColumn: "customer_id" }],
  },
  {
    name: "customers",
    rowCount: 16408,
    relevance: 0.91,
    columns: [
      {
        name: "customer_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Unique customer identifier.",
        metrics: measure(["c_1042", "c_1177", "c_2088"], 16408),
      },
      {
        name: "company_name",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Customer company or account name.",
        metrics: measure(["Acme Labs", "Trellis Health", "Summit Retail"], 16091),
      },
      {
        name: "segment",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Commercial customer segment.",
        metrics: measure(["enterprise", "mid_market", "startup"], 3),
      },
    ],
    foreignKeys: [],
  },
  {
    name: "products",
    rowCount: 428,
    relevance: 0.7,
    columns: [
      {
        name: "product_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Unique product identifier.",
        metrics: measure(["p_100", "p_101", "p_102"], 428),
      },
      {
        name: "product_name",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Product display name.",
        metrics: measure(["Signal Pro", "Relay", "Northstar API"], 428),
      },
      {
        name: "category",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Product category.",
        metrics: measure(["platform", "services", "data"], 3),
      },
    ],
    foreignKeys: [],
  },
  {
    name: "subscriptions",
    rowCount: 9102,
    relevance: 0.62,
    columns: [
      {
        name: "subscription_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Unique subscription identifier.",
        metrics: measure(["s_8801", "s_8802", "s_8803"], 9102),
      },
      {
        name: "customer_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Subscribed customer.",
        metrics: measure(["c_1042", "c_1177", "c_2088"], 8911),
      },
      {
        name: "mrr",
        dataType: "numeric(12,2)",
        nullable: false,
        semanticType: "measure",
        description: "Monthly recurring revenue.",
        metrics: measure(["99.00", "499.00", "1999.00"], 422, 29, 12000),
      },
    ],
    foreignKeys: [{ fromColumn: "customer_id", toTable: "customers", toColumn: "customer_id" }],
  },
  {
    name: "events",
    rowCount: 2104830,
    relevance: 0.4,
    columns: [
      {
        name: "event_name",
        dataType: "varchar",
        nullable: false,
        semanticType: "dimension",
        description: "Tracked product event name.",
        metrics: measure(["activated", "invited", "exported"], 88),
      },
      {
        name: "occurred_at",
        dataType: "timestamp",
        nullable: false,
        semanticType: "time",
        description: "UTC event timestamp.",
        metrics: measure(["2026-01-08", "2026-02-14", "2026-03-02"], 548),
      },
      {
        name: "customer_id",
        dataType: "bigint",
        nullable: false,
        semanticType: "key",
        description: "Customer who emitted the event.",
        metrics: measure(["c_1042", "c_1177", "c_2088"], 15004),
      },
    ],
    foreignKeys: [{ fromColumn: "customer_id", toTable: "customers", toColumn: "customer_id" }],
  },
];